version: '3.8'
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5433:5432'
        volumes:
            - db:/var/lib/postgresql/data
    queue:
        image: redis:7-alpine
        restart: always
        ports:
            - '6378:6379'
        # command: redis-server --save 20 1 --loglevel warning --requirepass redisPass
        volumes:
            - queue:/data
        networks:
            - bullmq
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            timeout: 5s
            retries: 3
volumes:
    db:
        driver: local
    queue:
        driver: local
networks:
    bullmq:
        driver: bridge
