version: '3.8'
services:
    # database for event indexing
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5433:5432'
        volumes:
            - db:/var/lib/postgresql/data
    queue:
        image: redis:7-alpine
        restart: always
        ports:
            - '6378:6379'
        # command: redis-server --save 20 1 --loglevel warning --requirepass redisPass
        volumes:
            - queue:/data
        networks:
            - bullmq
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            timeout: 5s
            retries: 3
    # Test database mainly for the indexer but can also be used by backend
    test_db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5434:5432'
        volumes:
            - test_db:/var/lib/postgresql/data
volumes:
    db:
        driver: local
    server_db:
        driver: local
    test_db:
        driver: local
    queue:
        driver: local
networks:
    bullmq:
        driver: bridge
